---
title: "Greensboro Treasure Hunt"
author: "#GnomeOnLoan"
output: html_document
toc: false
      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Congrats you got an treasure map in a box! Woohoo!


We've hidden clues and activities throughout downtown Greensboro for you to find (and refreshments to consume along the way, because hydration is key!)


We've provided a #GnomeOnLoan from the heralded Lauren collection because we all know that gnomes love adventures.


## What you will need:

* Wear something warm enough to fit light to moderate movement outside (aka check the weather outside my friends)  
* At least 1 functioning smart phone, that can also take and send pictures  
* The black bag of goodies!  
* Wallets (ids are important for adult oriented activities)   
* Water bottles suggested for hydration  


## Recommended Time of Day: 

Depending on your wits, this will likely take you __2-4 hours__. So it's best performed starting at 2pm on a Saturday. It is recommended that you park at the Greene street parking garage (or somewhere close to that). 

## Instructions:  
* Ensure NFC is enabled and tap your phone to the card (congrats! you probably already did this by getting to this site).  
* Use the clues provide to determine the locations for each step.   
* At the location, open the indicated section of the bag and consume the included items. Note that the numbered sections align with the clue number. You know have the required energy to proceed to complete the activity!   
* The password for the next clue is the location that you are currently at (always in lowercase, there is a hint at the bottom re number of letters). 


There are 6 locations and activities in total, you must take pictures at each location with our #GnomeOnLoan, Glenn. This will serve a proof that you and your adventure companions had the smarts to make it through. But please return Glenn back to Phil and Lauren. He likes adventures, but gets cranky when he's away from his gnome pack for too long.


## Go to clue 1!
Click on the "hamburger" on the top right and click the link that says "clue 1"









